### ISSUE TITLE
Is it Possible to Get at the Canvas Layer that cytoscape Writes to?

### ISSUE THREAD

**Issue by source-transformer** [sgratzl/cytoscape.js-layers#14]
Hi there, I was wondering if it is possible to get the layer that cytoscape uses for their rendering?  Otherwise is it possible to get a canvas "behind" their render?  I'm trying to write to either a canvas or SVG behind the cytoscape render - not just behind nodes or edges

I tried this - but canvasLayer is undefined:

```
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
		const layers = cy.layers( );
		const canvasLayer = layers.canvasLayer;
```

**Screenshots / Sketches**

**Context**

- Version: 2.3.1
- Browser: chrome

**Additional context**

**Comment by source-transformer** [comment]
I tried doing the following - but when I try rendering anything to this canvas - nothing appears:

```
		const cytoscapeElement = document.getElementById( 'cytoscapejs' );
		const cy: any = cytoscape( { container: cytoscapeElement } );

		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
		const cytoscapeLayers = cy.layers( );

		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
		const layers = cytoscapeLayers.getLayers();

		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
		const nodeLayer = cytoscapeLayers.nodeLayer;

		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
		const nodeLayerCanvas = nodeLayer.node;

		const cytoscapeCanvas = nodeLayerCanvas as HTMLCanvasElement;
```

I get a non null HTMLCanvasElement.  Is it possible this canvas reference is invalid after cytoscape renders?

**Comment by sgratzl** [comment]
can you create a reproducible example?

**Comment by source-transformer** [comment]
Ah - sorry - I should've expected you would want that.  I ended up switching to cytoscape-canvas and got it working with that instead.  I understand the approach of cytoscape-canvas is to effectively clone the cytoscape canvas and then listen for resize updates.  Whereas cytoscape-layers lets you get a reference to the actual canvas that cytoscape is using (i.e. both use different approaches).

The code I posted above was from the function I used to get a reference to the HTMLCanvasElement.  Then I handed that reference to another function that renders some polygons.  When I handed my own canvas (that I had created) or the "cloned canvas" from cytoscape-canvas - my rendering showed up.

Since I was getting a valid reference to the cytoscape canvas (using cytoscape-layers) - I had presumed there was some technical reason why my approach wasn't working.

Feel free to close this question as I don't think I'll be able to create a stackblitz example.  Based on your response it sounds like the approach I was using should've worked.

**Comment by source-transformer** [comment]
ah - I misunderstood.

Not sure if this is covered in your doc's - but the functions "insertBefore" and "append" - is this in reference to the layering (i.e. z value)?  Or is it in reference to intercepting mouse events?

Thanks!

**Comment by source-transformer** [comment]
Also - a suggestion.

In the code I'm writing when I generate a canvas "behind" cytoscape - I'd like access to the canvas context.

Would it make sense to add the following field:

```
ctx: CanvasRenderingContext2D
```

to this interface:

```
interface ICanvasLayer extends ITransformedLayer {
    readonly type: 'canvas';
    readonly callbacks: IRenderFunction[];
    callback(callback: IRenderFunction): ICanvasLayer;
}
```

It would allow users of the API to not just set everything to any - unless there is a "more correct way" to get access to the canvas context when you use the following:

```
const cytoscapeElement = document.getElementById( 'cytoscapejs' );
const cy: any = cytoscape( { container: cytoscapeElement } );

// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
const cytoscapeLayers: LayersPlugin = cy.layers( );

// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
const nodeLayer: ICytoscapeNodeLayer = cytoscapeLayers.nodeLayer;

// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
const canvasLayer = nodeLayer.insertBefore( 'canvas' ) as any;

// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
const canvasCtx: CanvasRenderingContext2D = canvasLayer.ctx;
```

**Comment by sgratzl** [comment]
take a look at https://codesandbox.io/s/cocky-wozniak-igez8q?file=/src/index.tsx

**Comment by source-transformer** [comment]
I _think_ this might have to do with my html.  


I tried adding callbacks for both append and insertBefore for canvas with the same result.  However, then I tried adding callbacks for svg and noticed something interesting.  Specifically the draw of the svg wasn't visible - but when I did a mouse over the svg element - it showed it was "at the bottom" of the screen - but out of view.

I did try inspecting the page and noticed the expected layers in the elements - but when you mouse over them - they are down at the bottom (past the limits of the scroll):
<img width="525" alt="image" src="https://user-images.githubusercontent.com/50280003/213558790-5ea715b6-8ec8-410a-83e0-192b50d556b3.png">


Unfortunately I'm not able to debug this any further.  Thanks for all the pointers nonetheless.

**Comment by source-transformer** [comment]
The highlighted div is the cytoscape render.

All of the other layers are the layers that cytoscape-layers that are being generated off screen.  It _looks_ like it is because the canvas layers are being generated with a zero height and width?

If it is helpful - I'm in the context of an angular app - within the context of:

```
<mat-drawer-content>
```

I'm wondering if this is a result of some kind of css or possibly how I've set up cytoscape in the html (i.e. not giving it an explicit height/width):

```
		<div class="page">
			<cytoscapejs
				id="cytoscapejs"
				[cytoscapeOptions]="cytoscapeOptions!"
				[autoFit]="autoFit"
				[applyCxBackgroundColor]="applyCxBackgroundColor"
				[cxData]="cxData"
				[cxConverters]="cxConverters"
				(coreChanged)="coreChanged($event)"
				(cxAttributeNameMapChanged)="cxAttributeNameMapChanged($event)"
				#cytoscopejs
			></cytoscapejs>
		</div>
```

**Comment by source-transformer** [comment]
I did some more testing with panning + zoom today and I think there is something very peculiar with cytoscape needing to have position absolute. 

I think this actually might explain the oddness with the layers created by cytoscape being "offscreen" or zero size.
