### ISSUE TITLE
  How can I reduce the redrawing of the canvas?

### ISSUE THREAD

**Issue by zhiangcai** [sgratzl/cytoscape.js-layers#29]
I created 4 canvas layers using the insert method and then used the renderPerNode method to draw the canvas. I used queryEachTime=true because I needed to update the custom canvas every time it was redrawn. When there is a large amount of data, dragging or scaling the canvas will feel too laggy. How can I use methods like requestAnimationFrame to reduce the redrawing of the canvas?

**Comment by sgratzl** [comment]
queryEachTime indicates that the collection of included nodes should be query each time. (cy.nodes("....")) Which is quite heavy. Not sure whether you need that. I guess you are looking more in the order of `updateOn = 'render'`. 

if you are using the canvas approach, why do you need four canvases? Why not just render everything at once\/

**Comment by zhiangcai** [comment]
1.  I set queryEachaTime=true because I found that when I delete a node, the custom layer does not automatically update, and the custom tag of the deleted node still exists


2.My requirement is to add node values, attribute values, and various labels to the node. The use of multiple layers is to update the canvas more efficiently. For example, if the label changes, I only need to update the label layer

---- Replied Message ----
| From | Samuel ***@***.***> |
| Date | 09/20/2023 21:46 |
| To | ***@***.***> |
| Cc | zhiangcai ***@***.***>,
Author ***@***.***> |
| Subject | Re: [sgratzl/cytoscape.js-layers] How can I reduce the redrawing of the canvas? (Issue #29) |

queryEachTime indicates that the collection of included nodes should be query each time. (cy.nodes("....")) Which is quite heavy. Not sure whether you need that. I guess you are looking more in the order of updateOn = 'render'.

if you are using the canvas approach, why do you need four canvases? Why not just render everything at once/

**Comment by zhiangcai** [comment]
1. I set queryEachaTime=true because I found that when I delete a node, the custom layer does not automatically update, and the custom tag of the deleted node still exists.

2. My requirement is to add node values, attribute values, and various labels to the node. The use of multiple layers is to update the canvas more efficiently. For example, if the label changes, I only need to update the label layer.

**Comment by zhiangcai** [comment]
Sorry, I noticed that when I upgraded the version, issue 1 has been fixed and I no longer need to set queryEachTime=true

**Comment by sgratzl** [comment]
> My requirement is to add node values, attribute values, and various labels to the node. The use of multiple layers is to update the canvas more efficiently. For example, if the label changes, I only need to update the label layer.

canvas is pretty fast, so I don't know whether you are getting any benefits because you also have overhead such as clearing and aligning each layer
