### ISSUE TITLE
How to renderPerEdge from Source to Target Positions

### ISSUE THREAD

**Issue by mttucl** [sgratzl/cytoscape.js-layers#38]
If edges have arrows, the path when using renderPerEdge goes from edge.sourceEndpoint() to edge.targetEndpoint(). Is it possible to render the path from edge.source().position() to edge.target().position()? It seems straightforward if the path is "straight" but not sure how to apply it to "bezier" style. Is there a way to achieve this or maybe consider an option for fullPath?

**Comment by sgratzl** [comment]
why do you need the path reversed? what style cannot be done if the default path (which is generated by cytoscape) is being used?

**Comment by mttucl** [comment]
Sorry if my OP was not clear. I hope [this pen](https://codepen.io/mtcl/pen/eYXjZLE) makes it clear. I would like the blue path to go from a to b nodes and not to target arrow. `edge.target().position()` gives the position of the node where `edge.targetEndpoint()` gives the position to target arrow. In case of straight line, I can directly use both psotions to draw a straight line. But for bezier curved line, I'm not sure how it can be extended to the target node.

**Comment by sgratzl** [comment]
hm. this plugin doesn't create the path but just piggy packs on the path from cytoscape. So, I'm not sure how to help you

this is the section of the code that does the edge rendering

https://github.com/sgratzl/cytoscape.js-layers/blob/9b2e63e6cd67bc39946956650fb52cb930ab5ccb/src/elements/edges.ts#L83-L109

**Comment by mttucl** [comment]
I found a fix by accessing `edge._private.rscratch` which has the path data. I updated the pen and here is the relevant code for anyone interested. If want to go from the center of the source node to the center of the target node, you can beginPath from edge.source().position() and extend to edge.target().position().
```
layers.renderPerEdge(layers.append('canvas'), (ctx, edge, path) => {
  ctx.strokeStyle = 'blue';
  ctx.stroke(path);
  const targetPos = edge.targetEndpoint();
  const pathData = edge._private.rscratch;
  ctx.beginPath();
  ctx.moveTo(pathData.endX, pathData.endY);
  ctx.lineTo(targetPos.x, targetPos.y);
  ctx.stroke(); 
});
```
