### ISSUE TITLE
The HTML canvas layer has bugs thats halts the rendering of the badges at correct places

### ISSUE THREAD

**Issue by Abhishek-kumar09** [sgratzl/cytoscape.js-layers#9]
We use cytoscape-layers plugin for rendering the informational badges with each node. We were using version `2.1.0` for a very long time, but since it had some unpredictable bugs and extra amount of re-rendering involved, we had to move to the latest version of this plugin. We had started using `v2.3.0`, but with the html layer it has got some serious bugs that are blocking the functional properties of our badges. In the code, there has been some calls to variables whose references aren't resolved giving uncaught errors, catching those errors block the behavioural properties of badges.

This is the error we get in production compiled build:
<img width="441" alt="Screenshot 2022-11-28 at 3 05 42 PM" src="https://user-images.githubusercontent.com/48255244/204244246-bc4d4d64-ef5b-4645-a35a-a51163b4edeb.png">
This error is arising from here:
https://github.com/sgratzl/cytoscape.js-layers/blob/74cd9a7beeac847c748c7e1327fc176e7f5cf5b5/src/layers/ABaseLayer.ts#L67-L69
fixing this particular error, the line 69 contains `this.update();` which throws further error of `update is not a function`.
This has been the error with the `v2.2.0` also.

The cytoscape badge in our UI looks like this: ![Screenshot 2022-11-28 at 3 19 32 PM](https://user-images.githubusercontent.com/48255244/204246875-a58df55b-331d-4ddd-a457-6758a32c2675.png)
on changing the position of node, the position of badge doesnt change and stay at the same place. 

**To Reproduce**

```js
const createBadge = (nodeId, render, cy,) => {
  /** @type {LayersPlugin} */
  const layers = cy.layers();

  layers.renderPerNode(
    layers.append("html"),
    (elem, node) => {
      if (node.data("id") === nodeId) {
        render(node, elem);
      }
    },
  );
};
```

2. `layers.append("html")` creates an html layer and render process has the styling config for it.
3.  On changing position of node, it throws an error as described above.

**Expected behavior**
On changing the position of the node, the badge should move at the correct place.

**Screenshots**

**Context**

- Version: 2.3.0 and 2.2.0
- Browser: Any

**Additional context**

**Comment by leecalcote** [comment]
Looking over the NPM package download stats, we've been using `2.1.0` for a couple years now and might be your biggest fans, @sgratzl. 😉
